### ISSUE TITLE
Isovar with pysam > 0.9.0

### ISSUE THREAD

**Issue by monikasekelja** [openvax/isovar#101]
Hi Alex,

Could you please update the Isovar's dependency on pysam=0.9.0 to pysam>0.9.0? It would make my life much easier if it could work with pysam=0.15.0.

Thank you for making this awesome piece of software!

- Monika

**Comment by iskandr** [comment]
Hey @monikasekelja @fdemasi  -- sorry to leave you hanging for so long. I finally started doing a rewrite of Isovar this year, which is now done (but being reviewed). The current master branch should work with pysam >= 0.15 but if you til the latest PR gets merged you'll get a lot of other improvements.
