### ISSUE TITLE
Change scripts into entry_points

### ISSUE THREAD

**Issue by iskandr** [openvax/isovar#35]
Since most of the code for scripts already lives in the `args` sub-package, I should probably just rename that to `cli` and add an entry_point for each script. 

See: https://chriswarrick.com/blog/2014/09/15/python-apps-the-right-way-entry_points-and-scripts/

**Comment by iskandr** [comment]
@julia326 If you want to learn about the layout of isvoar, this might be a good issue for you.

**Comment by julia326** [comment]
Sounds good - shall I reassign to myself?

**Comment by iskandr** [comment]
Sure!
