### ISSUE TITLE
option --use-duplicate-reads is ignores by isovar-protein-sequences.py 

### ISSUE THREAD

**Issue by drna** [openvax/isovar#94]
Thanks for creating isovar and make it available for others.

Some of my RNAs are of suboptimal quality resulting in many duplicated reads. 
isovar-protein-sequences.py was the option --use-duplicate-reads listed but I get exactly the same counts with and without it. 
I can send you a small bam file to test if necessary.

I really appreciate if you could look into this issue.

Regards,
Dina

**Comment by iskandr** [comment]
Hi @drna -- sorry for the very long (>1 year) delay. Are you still using Isovar? If so, would you want to send me test data on which this happens? I haven't been able to reproduce the problem on my latest branch but I'm not sure if I fixed the problem or if it's data-specific.
