### ISSUE TITLE
setup error: No such file or directory: 'isovar/__init__.py'

### ISSUE THREAD

**Issue by gilhornung** [openvax/isovar#95]
```
/bin>python isovar/setup.py
WARNING:root:Conversion of long_description from MD to RST failed
Traceback (most recent call last):
  File "isovar/setup.py", line 40, in <module>
    with open('isovar/__init__.py', 'r') as f:
IOError: [Errno 2] No such file or directory: 'isovar/__init__.py'
```

**Comment by timodonnell** [comment]
Try running `python setup.py install` from the isovar root directory. From your error it looks like you are running it from its parent directory.

**Comment by gilhornung** [comment]
I couldn't find the `__init__.py` in any directory.

At the end what I did was to find an _init__.py` file in an old commit, copied it to my local dir, and then run `setup.py`. It worked.

**Comment by iskandr** [comment]
Hey @gilhornung, it's still in master: https://github.com/openvax/isovar/blob/master/isovar/__init__.py

**Comment by iskandr** [comment]
OK close?
